services:
  bot:
    container_name: ${BOT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - tgrbot_network
    restart: unless-stopped
    volumes:
      - ./bot/logs:/app/bot/logs
      - ./bot/data:/app/bot/data


networks:
  tgrbot_network:
    driver: bridge
