services:
  bot:
    container_name: 'TGRBot_instance'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /bot/datab/db: /app/bot/datab/db 
      - /logs: /app/logs
