services:
  bot:
    container_name: ${BOT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "uv run python /app/bot/db_data/migrator.py"
    networks:
      - database
    depends_on:
      - postgres



  postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - datab:/app/datab/
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - database

volumes:
  datab:

networks:
  database:
    driver: bridge
