[project]
name = "random-bot-lite"
version = "0.1.0"
description = "Random telegram channel bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "dotenv>=0.9.9",
    "pydantic>=2.4.1",
    "pydantic-settings>=2.9.1",
    "random-word>=1.0.13",
]
